{
 "title": "JVM Details",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(base_gc_time_total_seconds,namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Heap Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(base_memory_usedHeap_bytes{namespace=\"$namespace\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(base_memory_committedHeap_bytes{namespace=\"$namespace\"})",
     "legendFormat": "Commited"
    },
    {
     "expr": "sum(base_memory_maxHeap_bytes{namespace=\"$namespace\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Total Non-Heap Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(base_memory_maxNonHeap_bytes{namespace=\"$namespace\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(base_memory_committedNonHeap_bytes{namespace=\"$namespace\"})",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Eden Space (Heap)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "vendor_memoryPool_Eden_Space_usage_bytes{namespace=\"$namespace\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "vendor_memoryPool_Eden_Space_usage_max_bytes{namespace=\"$namespace\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Survivor Space (Heap)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "vendor_memoryPool_Survivor_Space_usage_bytes{namespace=\"$namespace\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "vendor_memoryPool_Survivor_Space_usage_max_bytes{namespace=\"$namespace\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Old Generation (Heap)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "vendor_memoryPool_Tenured_Gen_usage_bytes{namespace=\"$namespace\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "vendor_memoryPool_Tenured_Gen_usage_max_bytes{namespace=\"$namespace\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Metaspace (Non-Heap)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "vendor_memoryPool_Metaspace_usage_bytes{namespace=\"$namespace\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "vendor_memoryPool_Metaspace_usage_max_bytes{namespace=\"$namespace\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Compressed Class Space (Non-Heap)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "vendor_memoryPool_Compressed_Class_Space_usage_bytes{namespace=\"$namespace\"}",
     "legendFormat": "Used - {{instance_label}}"
    },
    {
     "expr": "vendor_memoryPool_Compressed_Class_Space_usage_max_bytes{namespace=\"$namespace\"}",
     "legendFormat": "Max - {{instance_label}}"
    }
   ]
  },
  {
   "title": "CodeHeap 'profiled nmethods' (Non-Heap)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "vendor_memoryPool_CodeHeap_non_profiled_nmethods_usage_bytes{namespace=\"$namespace\"}",
     "legendFormat": "Used - {{instance_label}}"
    },
    {
     "expr": "vendor_memoryPool_CodeHeap_non_profiled_nmethods_usage_max_bytes{namespace=\"$namespace\"}",
     "legendFormat": "Max - {{instance_label}}"
    }
   ]
  },
  {
   "title": "CodeHeap 'non-profiled nmethods' (Non-Heap)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "vendor_memoryPool_CodeHeap_non_profiled_nmethods_usage_bytes{namespace=\"$namespace\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "vendor_memoryPool_CodeHeap_non_profiled_nmethods_usage_max_bytes{namespace=\"$namespace\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "CodeHeap 'non-nmethods' (Non-Heap)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "vendor_memoryPool_CodeHeap_non_nmethods_usage_bytes{namespace=\"$namespace\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "vendor_memoryPool_CodeHeap_non_nmethods_usage_max_bytes{namespace=\"$namespace\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "GC Count (Minor / Major)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "increase(base_gc_total{name=\"Copy1\",namespace=\"$namespace\"}[15s])",
     "legendFormat": "Minor GC"
    },
    {
     "expr": "increase(base_gc_total{name=\"MarkSweepCompact1\",namespace=\"$namespace\"}[15s])",
     "legendFormat": "Major GC"
    }
   ]
  },
  {
   "title": "System Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_cpu_systemLoadAverage{namespace=\"$namespace\"}",
     "legendFormat": "System Average Loade"
    },
    {
     "expr": "base_cpu_availableProcessors{namespace=\"$namespace\"}",
     "legendFormat": "CPU Size"
    }
   ]
  },
  {
   "title": "GC Pause Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(base_gc_time_total_seconds{name=\"MarkSweepCompact1\",namespace=\"$namespace\"}[1m])/rate(base_gc_total{name=\"MarkSweepCompact1\",namespace=\"$namespace\"}[1m])",
     "legendFormat": "Old Generation"
    },
    {
     "expr": "rate(base_gc_time_total_seconds{name=\"Copy1\",namespace=\"$namespace\"}[1m])/rate(base_gc_total{name=\"Copy1\",namespace=\"$namespace\"}[1m])",
     "legendFormat": "Young Generation"
    }
   ]
  },
  {
   "title": "Classes Unloaded",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_classloader_loadedClasses_count{namespace=\"$namespace\"}",
     "legendFormat": "Loaded Classes - Current"
    },
    {
     "expr": "base_classloader_unloadedClasses_total{namespace=\"$namespace\"}",
     "legendFormat": "Unloaded Classes - Total"
    }
   ]
  },
  {
   "title": "Threads (Deamon/Live)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_thread_daemon_count{namespace=\"$namespace\"}",
     "legendFormat": "Only Deamon"
    },
    {
     "expr": "base_thread_count{namespace=\"$namespace\"}",
     "legendFormat": "All Live"
    }
   ]
  }
 ]
}