{
 "title": "Opencell all in one dashboard",
 "description": "Opencell metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values({pod=~\"opencell-.\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values({pod=~\"opencell-.\"},pod)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Serveur Wildfly", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Load",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(base_cpu_systemLoadAverage{namespace=~\"$namespace\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Memory Load",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(base_memory_committedNonHeap_bytes{namespace=~\"$namespace\",pod=~\"$pod\"}) / sum(base_memory_maxHeap_bytes{namespace=~\"$namespace\",pod=~\"$pod\"}) *100"
    }
   ]
  },
  {
   "title": "Memory Heap",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "base_memory_usedHeap_bytes{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "used Heap {{namespace}} / {{pod}}"
    },
    {
     "expr": "base_memory_usedNonHeap_bytes{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "usedNonHeap {{namespace}} / {{pod}}"
    },
    {
     "expr": "base_memory_committedHeap_bytes{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "committed Heap {{namespace}} / {{pod}}"
    },
    {
     "expr": "base_memory_committedNonHeap_bytes{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "committed Non Heap {{namespace}} / {{pod}}"
    },
    {
     "expr": "base_memory_maxHeap_bytes{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "max Heap {{namespace}} / {{pod}}"
    },
    {
     "expr": "base_memory_maxNonHeap_bytes{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "max Non Heap {{namespace}} / {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Number",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "base_cpu_availableProcessors{namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Uptime of the JVM",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "base_jvm_uptime_seconds{namespace=~\"namespace\",pod=~\"pod\"}"
    }
   ]
  },
  {
   "title": " Node name",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 4 },
   "format": "short",
   "valueName": "name",
   "targets": [
    {
     "expr": "application_node_uname_info{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_cpu_systemLoadAverage{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "load 1m {{namespace}} / {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "base_memory_usedHeap_bytes{namespace=~\"$namespace\",pod=~\"$pod\"}+base_memory_usedNonHeap_bytes{namespace=~\"$namespace\",pod=~\"$pod\"}+base_memory_committedNonHeap_bytes{namespace=~\"$namespace\",pod=~\"$pod\"}+base_memory_committedHeap_bytes{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{namespace}} / {{pod}}"
    }
   ]
  },
  {
   "title": "Job Status",
   "type": "table-old",
   "description": "Status of Jobs",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{__name__=~\"application_is_running_.*\",namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Job Graph",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"application_is_running_.*\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{name}}-{{namespace}}"
    }
   ]
  },
  {
   "title": "Log",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate({namespace=~\"$namespace\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Log",
   "type": "logs",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\"}"
    },
    {
     "expr": "{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Base connection",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wildfly_datasources_pool_active_count{data_source=\"meveo\", namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "active count"
    },
    {
     "expr": "wildfly_datasources_pool_in_use_count{data_source=\"meveo\", namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "in use count"
    },
    {
     "expr": "wildfly_datasources_pool_idle_count{data_source=\"meveo\", namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "idle count"
    }
   ]
  },
  {
   "title": "Garbage Collector",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(base_gc_time_total_seconds{namespace=\"$namespace\",pod=\"$pod\"}[5m]) / rate(base_gc_total{namespace=\"$namespace\",pod=\"$pod\"}[5m])",
     "legendFormat": "{{namespace}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Base Thread",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_thread_count{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{namespace}} / {{pod}} "
    }
   ]
  }
 ]
}